[package]
name = "Snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.89.0"
find_folder = "0.3.0"
rand = "0.6.5"